### PR TITLE
vr9_avm_fritz7490.dts: Match led & key names with the actual hardware

### PR DESCRIPTION
**Pull request by hvegh**
Override key and led infos in "vr9_avm_fritzxx90.dtsi" for AVM FRITZ!Box 7490,
in order to match the names on hardware.

Configuration 7490:
  [LED] use GPIO 45 for 'gpio_avm_led_power'
  [LED] use GPIO 47 for 'gpio_avm_led_internet'
  [LED] use GPIO 36 for 'gpio_avm_led_festnetz'
  [LED] use GPIO 35 for 'gpio_avm_led_wlan'
  [LED] use GPIO 33 for 'gpio_avm_led_info'
  [LED] use GPIO 46 for 'gpio_avm_led_info_red'
  [BUTTON] use GPIO 29 for 'gpio_avm_button_wlan'
  [BUTTON] use GPIO 1 for 'gpio_avm_button_dect

For reference:

Configuration 5490:
  [LED] use GPIO 45 for 'gpio_avm_led_power'
  [LED] use GPIO 47 for 'gpio_avm_led_fiber'
  [LED] use GPIO 36 for 'gpio_avm_led_wlan'
  [LED] use GPIO 35 for 'gpio_avm_led_internet'
  [LED] use GPIO 33 for 'gpio_avm_led_info'
  [LED] use GPIO 46 for 'gpio_avm_led_info_red'
  [BUTTON] use GPIO 29 for 'gpio_avm_button_wlan'
  [BUTTON] use GPIO 1 for 'gpio_avm_button_dect'

Configuration 3390:
  [LED] use GPIO 45 for 'gpio_avm_led_power'
  [LED] use GPIO 47 for 'gpio_avm_led_lan_all'
  [LED] use GPIO 36 for 'gpio_avm_led_wlan'
  [LED] use GPIO 35 for 'gpio_avm_led_pppoe'
  [LED] use GPIO 33 for 'gpio_avm_led_info'
  [BUTTON] use GPIO 29 for 'gpio_avm_button_wlan'
  [BUTTON] use GPIO 1 for 'gpio_avm_button_wps'

Signed-off-by: Henk Vergonet <henk.vergonet@gmail.com>

### CODE REVIEW

**Comment by hvegh** [comment]
Tested and working, 
What a wonderful progress has been made on the xx90 series!

I can also test on 5490 if needed. Please know if I can help.

**Comment by jschwartzenberg** [comment]
> I can also test on 5490 if needed. Please know if I can help.

That would be great actually. I haven't been able to get the newer revisions of this repo to install and boot on my 5490 yet. There are still some things I have to try, but I haven't found the time yet. Also I have not been able to establish a connection over the AON fiber port at all yet.

**Comment by kestrel1974** [comment]
I think I can just include it in my fork. However, in the old PRs for 3490 there were a lot of discussions about not having comments in dtb or dtsi files and other stuff. So similar to what I have done in my fork, a lot of stuff will never survive the review of a real PR.

**Comment by kestrel1974** [comment]
@hvegh With regards to help. I was trying to get the other two LAN ports of the 5490 to work, which is hard without the device and without a soldered serial console to see possible kernel panics, but it seems to be difficult to get it booted with the values in the device tree from back then, e.g. what I have removed from commit 228b0f2. I don't even know if those values are at the right position nor how to integrate two different switches in the same device tree. Its also possible that this switch needs to be configured outside of the gswip stuff as separate device. But the mdio register of this additional switch is 0x00 with regards to the AVM sources.
I took the values from what the AVM code does (essentially changed the set function to print the values at initialization time), but it did not seem to have worked for the device tree config. I don't know if the driver is still active in the kernel config, [but this is the device](https://github.com/openwrt/openwrt/blob/master/target/linux/generic/files/drivers/net/phy/ar8327.c).
Its enabled [by this patch](https://github.com/openwrt/openwrt/blob/master/target/linux/generic/hack-5.10/700-swconfig_switch_drivers.patch) and looks like [its already enabled](https://github.com/openwrt/openwrt/search?q=CONFIG_AR8216_PHY).
There are [configuration samples here](https://github.com/openwrt/openwrt/search?q=ar8327.c). But its too difficult to test any changes without owning the device.

**Comment by hvegh** [comment]
> I think I can just include it in my fork. However, in the old PRs for 3490 there were a lot of discussions about not having comments in dtb or dtsi files and other stuff. So similar to what I have done in my fork, a lot of stuff will never survive the review of a real PR.

Yes I know...
I am not sure why there's so much opposition to comments in the dts. As these files are the ideal location for making small comments on the particularities of a specific board, as a developer I find these quite usefull. 

Anyway if trouble arises I will be happy to remove. Most important thing is now to get the basics mainlined....  So if comments are blocking well I guess they should be removed... ;)

**Comment by hvegh** [comment]
Regarding dts include files:

There is tradeoff with regard to dtsi include files: On the one hand shared code is good because it lets you code generalized use cases but at a cost of additional dependencies.

Also keep in mind that in DTS is that all nodes are "ORed" together, meaning; when you define somewhere a.b and somewhere else a.c you will end up with a.b and a.c.  For board specifics like leds and buttons this is generally not good. That why i added the _delete-node_. 

So I would argue to move the led and button stuff from the ...xx90.dtsi file to the specific board.dts so we can remove the _delete-node_ construct. We may need todo this also for the ethernet setup if we discover changes between 7490 and 5490.

**Comment by hvegh** [comment]
> those values are at the right position nor how to integrate two different switches in the same device tree. Its also possible that this switch needs to be configured outside of the gswip stuff as separate device. But the mdio register of this additional switch is 0x00 wit

Thats relevant information, just looking at the pcb of the 5490 it seams the ports are directly coupled to the Lantic chip I do not see additional ARxxx switches as the case in the 7490. The ARxxx code is definitely used.  

That means we should probably move the phy definitions also to the board specific setup. I will experiment, the ethernet ports on the 7490 are working brilliantly I can say...

**Comment by hvegh** [comment]
> > those values are at the right position nor how to integrate two different switches in the same device tree. Its also possible that this switch needs to be configured outside of the gswip stuff as separate device. But the mdio register of this additional switch is 0x00 wit
> 
> Thats relevant information, just looking at the pcb of the 5490 it seams the ports are directly coupled to the Lantic chip I do not see additional ARxxx switches as the case in the 7490. The ARxxx code is definitely used.
> 
> That means we should probably move the phy definitions also to the board specific setup. I will experiment, the ethernet ports on the 7490 are working brilliantly I can say...

Nope I was wrong, on closer inspection there is indeed an additional [4 port switch](https://github.com/Deoptim/atheros/raw/master/QCA8334-datasheet.pdf):

assuming they have connected as such:
```
fiber ---serdes----AR8033-AL1A----rgmii-->
       >--switch QCA8334-AL3C / port 6

lan1 ---------------------------------------------- Lantiq (internal phy)
lan2 ---------------------------------------------- Lantiq (internal phy)
lan3 ---- switch QCA8334-AL3C / port 2 or 3
lan4 ---- switch QCA8334-AL3C / port 2 or 3
          switch QCA8334-AL3C / port 0 ----rgmii--- Lantiq

      wlan QCA9880-BR4A Peregrine (ac)---rgmii----- Lantiq
      wlan QCA9558-AT4A Scorpion (n)-----rgmii----- Lantiq

```

I think the [optical transciever](http://www.sopto.com.cn/upload/201907/23/201907231540142360.pdf) could also have been connected to the switch directly.

I think we need to split off the networking stuff, and possibly look into the [AVM sourcecode](https://osp.avm.de/fritzbox/fritzbox-5490/source-files-FRITZ.Box_5490-06.84.tar.gz) for the port configuration of the switch.

Anyway that it for now...

**Comment by hvegh** [comment]
Some usefull info:

https://elixir.bootlin.com/linux/latest/source/Documentation/devicetree/bindings/net/dsa/qca8k.txt

**Comment by kestrel1974** [comment]
> I think the [optical transciever](http://www.sopto.com.cn/upload/201907/23/201907231540142360.pdf) could also have been connected to the switch directly.
> 
> I think we need to split off the networking stuff, and possibly look into the [AVM sourcecode](https://osp.avm.de/fritzbox/fritzbox-5490/source-files-FRITZ.Box_5490-06.84.tar.gz) for the port configuration of the switch.
> 
> Anyway that it for now...

Thanks for looking into it, thats what [I observed too from the config](https://github.com/kestrel1974/lantiq7portswitch/blob/master/avm_cpmac/configs/config_HW223.h) and here is a pointer to the location where all those values I had removed in the DTB for the second switch get written [from the sources](https://github.com/kestrel1974/lantiq7portswitch/blob/master/avm_cpmac/phy/avmnet_ar8326.c#L371), I had put the networking part from the AVM sources into a repository for discussion purposes when they were implementing gwsip.

From AVMs config the optical transceiver is connected like any of the gigabit ports. May it does not have to be configured as wan like I did in the script, the wan port [is not added with the config script](https://github.com/kestrel1974/openwrt/blob/fritzbox7490/target/linux/lantiq/xrx200/base-files/etc/board.d/02_network#L33) maybe for 5490 it has to be done like for the zyxel device 3 lines above.

**Comment by kestrel1974** [comment]
> Some usefull info:
> 
> https://elixir.bootlin.com/linux/latest/source/Documentation/devicetree/bindings/net/dsa/qca8k.txt

@hvegh Yep I tried to draw conclusions from that, but I guess I have put the stuff into the wrong place. To me it looks like that AVM has moved the gpio numbers up for the directly connected ports to be able to use the mdio reg 0x00 till 0x04 for the additional switch. But adding the switch to mdio_gwsip seemed not to have a positiv effect on the working two other ethernet ports.

**Comment by hvegh** [comment]
> From AVMs config the optical transceiver is connected like any of the gigabit ports. May it does not have to be configured as wan like I did in the script, the wan port [is not added with the config script](https://github.com/kestrel1974/openwrt/blob/fritzbox7490/target/linux/lantiq/xrx200/base-files/etc/board.d/02_network#L33) maybe for 5490 it has to be done like for the zyxel device 3 lines above.

Most of the time users would want to connect to their ISP using the fiber port so "wan" makes sense in that case. From a technical perspective the link just behaves like any other ethernet port. If it is your ISP you are connecting to, the first thing you would want todo is feed it to your firewall.  So in that sense it is different.

**Comment by jschwartzenberg** [comment]
> Most of the time users would want to connect to their ISP using the fiber port so "wan" makes sense in that case. From a technical perspective the link just behaves like any other ethernet port. If it is your ISP you are connecting to, the first thing you would want todo is feed it to your firewall. So in that sense it is different.

I'm curious if you managed to get this port working. When I tried to establish a PPPoE connection over `wan.6` to my ISP, I did not manage to bring it up yet. The same settings work for my Omnia.

**Comment by hvegh** [comment]
> > Most of the time users would want to connect to their ISP using the fiber port so "wan" makes sense in that case. From a technical perspective the link just behaves like any other ethernet port. If it is your ISP you are connecting to, the first thing you would want todo is feed it to your firewall. So in that sense it is different.
> 
> I'm curious if you managed to get this port working. When I tried to establish a PPPoE connection over `wan.6` to my ISP, I did not manage to bring it up yet. The same settings work for my Omnia.

Unfortunately only VDSL2 is supported here so I can't test. If there's still issues with the 4 ports switch, maybe this needs to be fixed first.

**Comment by hvegh** [comment]
vdsl2 working, 
lan1-4 working
wifi untested.

**Comment by kestrel1974** [comment]
@hvegh Unfortunately moving to the new DST API does not solve the issue, that e.g. 7490 can have Micron and Macronix NAND. Your solution only works for Micron NAND. I have been [discussing this with the kernel maintainers](http://lists.infradead.org/pipermail/linux-mtd/2021-August/087732.html) but no solution. It looks like we need to do the same as for 3370, which has two DTB flavours, one for [Micron](https://github.com/openwrt/openwrt/blob/master/target/linux/lantiq/files/arch/mips/boot/dts/lantiq/vr9_avm_fritz3370-rev2-micron.dts) with what you did and one for the [Hynix](https://github.com/openwrt/openwrt/blob/master/target/linux/lantiq/files/arch/mips/boot/dts/lantiq/vr9_avm_fritz3370-rev2-hynix.dts), which also works for all others (e.g. ST Micro, Macronix and Toshiba), that require ecc-soft. Thats probably required for 3490 too, I don't know if 5490 has Toshiba NAND only.
The [3370 wiki](https://openwrt.org/toh/avm/fritz.box.wlan.3370) essentially talks about how to figure out which image to use and the [commit message](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=0b62fe5ed87ecac52301096b15abb69f96117c8c) about the reasons and that a change will probably not make it into the kernel, which is what I am fighting with.

In the end, we probably need to create 6 devices, 3490 micron, 3490 non-micron and so on.

**Comment by hvegh** [comment]
> @hvegh Unfortunately moving to the new DST API does not solve the issue, that e.g. 7490 can have Micron and Macronix NAND. Your solution only works for Micron NAND. I have been [discussing this with the kernel maintainers](http://lists.infradead.org/pipermail/linux-mtd/2021-August/087732.html) but no solution. It looks like we need to do the same as for 3370, which has two DTB flavours, one for [Micron](https://github.com/openwrt/openwrt/blob/master/target/linux/lantiq/files/arch/mips/boot/dts/lantiq/vr9_avm_fritz3370-rev2-micron.dts) with what you did and one for the [Hynix](https://github.com/openwrt/openwrt/blob/master/target/linux/lantiq/files/arch/mips/boot/dts/lantiq/vr9_avm_fritz3370-rev2-hynix.dts), which also works for all others (e.g. ST Micro, Macronix and Toshiba), that require ecc-soft. Thats probably required for 3490 too, I don't know if 5490 has Toshiba NAND only.
> The [3370 wiki](https://openwrt.org/toh/avm/fritz.box.wlan.3370) essentially talks about how to figure out which image to use and the [commit message](https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=0b62fe5ed87ecac52301096b15abb69f96117c8c) about the reasons and that a change will probably not make it into the kernel, which is what I am fighting with.
> 
> In the end, we probably need to create 6 devices, 3490 micron, 3490 non-micron and so on.

Ok, horror...
Then the best solution is to handle this in the flash driver as it probably needs to probe the chip anyway in order to get the specifics of the memory organization... 

Maybe for mainline WRT tree it is acceptable to use software ECC in all cases. And then at some point remove the ECC when flash driver is able to figure this out on its own...

I have recently switched from ADSL to VDSL2 so I dug up the 7490 and I must say it is working brilliantly, there are probably quite a few 7490's out there so it would be nice to have this support mainlined..  

The 7490 for a few days running with the initramfs-image. I must say I am quite happy:
- USB3 working, tested with usb storage device..
- Lan ports 1-4 working
- VDSL2 drver, working, exactly the same speeds as with the ISP modem.
- The WASP with both wlan adapters working, need a few retries to upload the image...
 
So pretty impressed!

The only remaining thing in my opinion is to check if the flash partitions are optimal and if we have a good method to upload to flash while still being able to go back to the stock firmware image...

**Comment by timocapa** [comment]
out of curiosity, why fritzos 6.x instead of 7.x?

**Comment by hvegh** [comment]
> out of curiosity, why fritzos 6.x instead of 7.x?

That is what is in my flash. The problem is that Fritz decided to swap partitions after version 6... See https://openwrt.org/toh/avm/fritz.box.7490#bootlogs

**Comment by hvegh** [comment]
I have flashed OpenWrt to the NAND partitions mtd2 and mtd3 see for explanation on howto flash and bootlog:

[Opwnwrt Wiki Fritzbox 7490](https://openwrt.org/toh/avm/fritz.box.7490#experimental_versions)

Working great!

**Comment by kestrel1974** [comment]
@hvegh Thanks for you work, I currently have no much time, I will merge later.
Another question, would it be ok for you to split off the dtbs and e.g. remove the xx90 include completely and create two (one micron and one non micron) dtb similar to 3370, as that seems the way to go given the kernel developers do not accept auto detection on the NAND chip issue.

**Comment by hvegh** [comment]
> @hvegh Thanks for you work, I currently have no much time, I will merge later.
> Another question, would it be ok for you to split off the dtbs and e.g. remove the xx90 include completely and create two (one micron and one non micron) dtb similar to 3370, as that seems the way to go given the kernel developers do not accept auto detection on the NAND chip issue.

Bummer... 
I am not sure what the dependencies are beside the basic board configs and DTS stuff, at a minimum I would assume a bump to lantiq 5.10 kernel..

**Pull request merged**
